name: recipe_app
description: "Cooking Recipe App"
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  http: ^1.2.2
  http_interceptor: ^2.0.0
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
   - assets/images/
