// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf5tksBIWA0TnznRqh_z_vZxSeb02X97o',
    appId: '1:589913641646:android:922b25bcf7c6a9e11e133f',
    messagingSenderId: '589913641646',
    projectId: 'recipe-app-1a6e6',
    storageBucket: 'recipe-app-1a6e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2RsNeDMimo0JOvB_t577XytmtqhsDb10',
    appId: '1:589913641646:ios:8dfa4fad7c9075561e133f',
    messagingSenderId: '589913641646',
    projectId: 'recipe-app-1a6e6',
    storageBucket: 'recipe-app-1a6e6.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDglIWWyYAbSiXjl0AayI5RnaV9n3DKmcQ',
    appId: '1:589913641646:web:5481cbe4ce5991e11e133f',
    messagingSenderId: '589913641646',
    projectId: 'recipe-app-1a6e6',
    authDomain: 'recipe-app-1a6e6.firebaseapp.com',
    storageBucket: 'recipe-app-1a6e6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2RsNeDMimo0JOvB_t577XytmtqhsDb10',
    appId: '1:589913641646:ios:8dfa4fad7c9075561e133f',
    messagingSenderId: '589913641646',
    projectId: 'recipe-app-1a6e6',
    storageBucket: 'recipe-app-1a6e6.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDglIWWyYAbSiXjl0AayI5RnaV9n3DKmcQ',
    appId: '1:589913641646:web:e191b0ba0dc1f77e1e133f',
    messagingSenderId: '589913641646',
    projectId: 'recipe-app-1a6e6',
    authDomain: 'recipe-app-1a6e6.firebaseapp.com',
    storageBucket: 'recipe-app-1a6e6.firebasestorage.app',
  );

}